[functions.api]
 included_files = ["netlify/functions/module/**", "netlify/functions/util/**", "netlify/functions/plugins/**", "netlify/functions/package.json", "netlify/functions/public/**"]
 external_node_modules = ['express', 'axios', 'qrcode', 'music-metadata', 'md5', 'music-metadata', 'pac-proxy-agent', 'express-fileupload', 'safe-decode-uri-component', 'tunnel', 'yargs', 'tslib', 'vm2', 'xml2js']
 node_bundler = 'esbuild'
[[redirects]]
 force = true
 from = '/*'
 status = 200
 to = '/.netlify/functions/api/:splat'